profiles:
  default:
    modules:
      - shell/zsh
      - tools/git
      - tools/ssh
  mac:
    modules:
      - profiles/macOS
  server:
    modules:
      - profiles/beets
  work:
    modules:
      - profiles/work