profiles:
  default:
    modules:
      - apps/proton-pass
      - editors/helix
      - shell/zsh
      - tools/fzf
      - tools/git
      - tools/gh
      - tools/lazygit
      - tools/mise
      - tools/rg
      - tools/ssh
      - tools/tldr
  home:
    modules:
      - apps/signal
  mac:
    modules:
      - profiles/macOS
      - terminals/iterm2
  server:
    modules:
      - profiles/beets
  work:
    modules:
      - profiles/work